language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
- 5.6
- 7.0
- hhvm

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.6 WP_MULTISITE=0
- WP_VERSION=4.5 WP_MULTISITE=0

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.2
      env: WP_VERSION=latest WP_MULTISITE=0
  exclude:
    - php: hhvm
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=4.5 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit