language: php

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=4.5 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=4.5 WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.2
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=latest WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit